config/routes.rb
HealthyHabits::Application.routes.draw do
  #resources :products
  resources :contacts
  resources :testimonials
  resources :pages

  match '/products_page', :to=>'products#products_page'

  authenticated :user do
    root :to => "pages#show", :id => 'home'
  end
  root :to => "pages#show", :id => 'home'

  devise_for :users
  resources :users

  #devise_scope :user do
  #  get '/login', :to => "devise/sessions#new"
  #  get '/signup', :to => "devise/registrations#new"
  #  post '/users/sign_out' => 'devise/sessions#destroy'
  #  post '/logout' => 'devise/sessions#destroy'
  #end

  match '/cleanse_notice', :to => 'contacts#cleanse_notice'
  match '/microscopy_notice', :to => 'contacts#microscopy_notice'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#

class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :trackable, :validatable, :rememberable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  def admin?
    self.has_role? :admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'

    @user = User.find(params[:id])
    if (params[:user][:password] == "")
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    if @user.update_attributes(params[:user])
      # set to admin if flag set
      if params["Administrator"].nil?
        @user.remove_role :admin
      else
        @user.add_role :admin
      end

      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."  + @user.errors.full_messages.to_sentence
    end
  end

  def new
    @newuser = User.new
  end

  def create
    @newuser = User.new(params[:user])
    if @newuser.save
      redirect_to users_path
    else
      render :new, :alert => "Error creating user: " + @newuser.errors.full_messages.to_sentence
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

    <%= render 'shared/error_messages', :object => f.object %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      Administrator: <%= check_box_tag("Administrator", value = "1",
                        checked = f.object.admin?) %>
      <br/>

    </div>
    <div class="actions">
      <%= f.submit "Submit", :class=>"span1 btn btn-success btn-mini" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>
<% if current_user.has_role? :admin %>
    <%= render "form", :user => @user %>
<% else %>
    Only Administrators Can Create A New User...
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>

<%= link_to "Add User", new_user_path, :class=>"btn btn-mini btn-success" %>
<br/>
<div class="span8">
<table class="table table-striped">
  <thead>
    <tr>
      <th style="text-align: center;">User</th>
      <th colspan="3" style="text-align: center;">Operations</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td class="span4">
        <strong><%= link_to user.name, user %></strong> <br/>
        <%= user.email  %>
      </td>
      <td>
        <% unless user.roles.first.nil? %>
            <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini btn-info btn_test span1" type="button">
              <%= user.roles.first.name.titleize %>
            </a>
            <%= render user %>
        <% end %>
      </td>

      <td>
        <%= link_to "<i class='icon-save icon-large'></i>".html_safe, edit_user_path(user), :class=>"span1" %>
      </td>

      <td>
        <%= link_to("<i class='icon-trash icon-large'></i>".html_safe, user_path(user), :data => { :confirm => "Are you sure?" },
                      :method => :delete, :class => 'span1') unless user == current_user %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/new.html.erb
<h1>Create New User</h1>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>
<% if current_user.has_role? :admin %>
    <%= render "form", :user => @newuser %>
<% else %>
    Only Administrators Can Create A New User...
<% end %>

app/views/users/show.html.erb
<h3>User</h3>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>