config/routes.rb
HealthyHabits::Application.routes.draw do
  #resources :products
  resources :contacts
  resources :testimonials
  resources :pages

  match '/products_page', :to=>'products#products_page'

  authenticated :user do
    root :to => "pages#show", :id => 'home'
  end
  root :to => "pages#show", :id => 'home'

  devise_for :users
  resources :users

  #devise_scope :user do
  #  get '/login', :to => "devise/sessions#new"
  #  get '/signup', :to => "devise/registrations#new"
  #  post '/users/sign_out' => 'devise/sessions#destroy'
  #  post '/logout' => 'devise/sessions#destroy'
  #end

  match '/cleanse_notice', :to => 'contacts#cleanse_notice'
  match '/microscopy_notice', :to => 'contacts#microscopy_notice'
end

app/views/pages/_form.html.erb
<script type="text/javascript" src="/js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save," +
            "advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime," +
            "preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen," +
            "noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft," +
            "justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect," +
            "fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|," +
            "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor," +
            "image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|," +
            "charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|," +
            "styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars," +
            "nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_resizing : true,
//
//        // Skin options
//        skin : "o2k7",
//        skin_variant : "silver",
//
//        // Example content CSS (should be your site CSS)
        //content_css : "/assets/style.css",
//        style_formats : [
//            {title: 'Line Height', inline: 'span', styles: {line-height: '150%'}},
//            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
//            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
//            {title: 'Example 1', inline: 'span', classes: 'example1'},
//            {title: 'Example 2', inline: 'span', classes: 'example2'},
//            {title: 'Table styles'},
//            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
//        ],
//
//        // Drop lists for link/image/media/template dialogs
////        template_external_list_url : "js/template_list.js",
////        external_link_list_url : "js/link_list.js",
////        external_image_list_url : "js/image_list.js",
////        media_external_list_url : "js/media_list.js",
//
//

        style_formats: [
            {title: 'Line Height 1.5', inline: 'span', styles: {lineHeight: '250%'}},
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],
        formats: {
            alignleft: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'left'},
            aligncenter: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'center'},
            alignright: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'right'},
            alignfull: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'full'},
            bold: {inline: 'span', 'classes': 'bold'},
            italic: {inline: 'span', 'classes': 'italic'},
            underline: {inline: 'span', 'classes': 'underline', exact: true},
            strikethrough: {inline: 'del'},
            customformat: {inline: 'span', styles: {color: '#00ff00', fontSize: '20px'}, attributes: {title: 'My custom format'}}
        }
    });



</script>

<%= simple_form_for @page do |f| %>
    <%= f.input :name %>
    <%= f.input :title %>

    <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>

    <%= f.button :submit, :class=>"btn btn-mini btn-success" %>
    <%= link_to 'Cancel', pages_url, :class=>"btn btn-mini" %>
<% end %>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>

<%= render "form" %>

app/views/pages/index.html.erb
<h1>Page Manager</h1>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>
<% if !current_user.nil? && current_user.has_role?(:admin) %>
    <%= link_to "Create New Page", new_page_path, :class=>"btn btn-mini btn-success btn_test" %> <br/>
<% end %>
<table class="table table-striped">
  <% @pages.each do |pg| %>
      <tr>
        <td><%= link_to pg.name, "/pages/#{pg.name}" %></td>
        <td><%= pg.title %></td>
        <td><%= link_to " edit ", edit_page_path(pg), :class=>"btn btn-mini btn-primary btn_test span1" %></td>
        <td><%= link_to "delete", pg, :method => :delete,
                        :confirm => "You sure you want to delete " + pg.name + "?",
                        :title => "Delete #{pg.name}",
                        :class => "btn btn-danger btn-mini btn_test span1" %></td>
      </tr>
  <% end %>
</table>

app/views/pages/new.html.erb
<h1>Create New Page</h1>
<%= hidden_field_tag( "page_name", "admin", :id => "page_name") %>

<%= render "form" %>

app/views/pages/show.html.erb
<% if !current_user.nil? && current_user.has_role?(:admin) %>
    <br/>
    <%= link_to "edit", edit_page_path(@page.id), :class=>"btn btn-mini" %>
    <%= link_to "pages", pages_path, :class=>"btn btn-mini" %>
<% end %>
<h1><%=  @title %></h1>

<%= hidden_field_tag( "page_name", @page.name, :id => "page_name") %>
<div class="page_body">
<%= @content.html_safe %>
</div>