config/routes.rb
HealthyHabits::Application.routes.draw do
  #resources :products
  resources :contacts
  resources :testimonials
  resources :pages

  match '/products_page', :to=>'products#products_page'

  authenticated :user do
    root :to => "pages#show", :id => 'home'
  end
  root :to => "pages#show", :id => 'home'

  devise_for :users
  resources :users

  #devise_scope :user do
  #  get '/login', :to => "devise/sessions#new"
  #  get '/signup', :to => "devise/registrations#new"
  #  post '/users/sign_out' => 'devise/sessions#destroy'
  #  post '/logout' => 'devise/sessions#destroy'
  #end

  match '/cleanse_notice', :to => 'contacts#cleanse_notice'
  match '/microscopy_notice', :to => 'contacts#microscopy_notice'
end

app/models/testimonial.rb
# == Schema Information
#
# Table name: testimonials
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  comment                :text
#  date                   :date
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  thumbnail_file_name    :string(255)
#  thumbnail_content_type :string(255)
#  thumbnail_file_size    :integer
#  thumbnail_updated_at   :datetime
#

class Testimonial < ActiveRecord::Base
  attr_accessible :comment, :date, :name, :thumbnail

  has_attached_file :thumbnail,
    :styles => {
        thumb: '100x100>',
        full: '300x300>'
    }

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  load_and_authorize_resource
  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
  def new
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(params[:testimonial])

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render json: @testimonial, status: :created, location: @testimonial }
      else
        format.html { render action: "new" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonials/1
  # PUT /testimonials/1.json
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(params[:testimonial])
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "/assets/style.css"

        // Drop lists for link/image/media/template dialogs
//        template_external_list_url : "js/template_list.js",
//        external_link_list_url : "js/link_list.js",
//        external_image_list_url : "js/image_list.js",
//        media_external_list_url : "js/media_list.js",


    });

</script>

<%= simple_form_for(@testimonial) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :thumbnail, :class=>"file_upload_btn" %>

    <% unless @testimonial.thumbnail.blank? %>
        <%= image_tag @testimonial.thumbnail.url(:thumb), :id=>"testimonial_image" %>
    <% end %>

    <%= f.input :name %>

    <%= f.text_area :comment, :class => "tinymce", :rows => 20, :cols => 120 %>

    <%= f.input :date %>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<% if !current_user.nil? && current_user.admin?  %>
<h1>Testimonial Management</h1>

<%= link_to 'New Testimonial', new_testimonial_path, :class=>"btn btn-small btn-success btn_test" %>
<br /><br/>

<table class="table table-striped testimonial_table">
  <tr>
    <th>Name/Date</th>
    <th>Comment</th>
    <th></th>

    <th colspan="2">Operations</th>

  </tr>

<% @testimonials.each do |testimonial| %>
  <tr>
    <td>
      <strong> <%= testimonial.name %><br/></strong>

      <% unless testimonial.thumbnail.blank? %>
          <%= image_tag testimonial.thumbnail.url(:thumb) %> <br/>
      <% end %>
      <%= testimonial.date %>
    </td>
    <td class="span5"><%= testimonial.comment.html_safe %></td>
    <td></td>
    <td><%= link_to 'Edit', edit_testimonial_path(testimonial), :class=>"btn btn-small btn-primary btn_test" %></td>
    <td><%= link_to 'Destroy', testimonial, method: :delete,
                    data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger btn_test" %></td>
  </tr>
<% end %>
</table>
<% else %>
    <h1>Public Testimonials Page</h1>
    <p>The following are real testimonials from our past clients.  We look forward to adding your story to this page!</p>
    <table class="table table-striped">
      <% @testimonials.each do |testimonial| %>
          <tr>
            <td>
              <strong><%= testimonial.name %></strong> - <%= testimonial.date %> <br/><br/>
              <%= image_tag testimonial.thumbnail.url(:thumb), :class=>"testimonial_image" %>
              <%= testimonial.comment.html_safe %>

            </td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimonial.name %>
</p>

<p>
  <%= image_tag @testimonial.thumbnail.url(:thumb) %><br/>
  <b>Comment:</b> <br/>

  <%= @testimonial.comment.html_safe %>
</p>

<p>
  <b>Date:</b>
  <%= @testimonial.date %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>